### ISSUE TITLE
Wrong conversion in wintertime

### ISSUE THREAD

**Issue by jeanpaul** [mulot/BeatTime#4]
The conversion from internet time to local time had a bug, I’m afraid. I just converted local time to beats and then back, and there was an hour difference.

My time zone is CET (Amsterdam), winter time. I converted 20:00 to @833, then converted @833 back, and got 20:59. 

Latest version on iOS 16.1.1

**Comment by mulot** [comment]
Fixed in release 1.2.1

**Comment by jeanpaul** [comment]
Awesome, thanks for the quick response!
